= BDD Trader application

The BDD Trader application demonstrates BDD and test automation techniques using Serenity BDD. The application allows users to create portfolios of shares using real market data.

The application is made of several components
* A set of REST API endpoints
* An AngularJS frontend

== Building the project

This project uses a Maven build. To build an executable jar, run `mvn package`.
This will produce a jar in the `target` directory.

=== Running the application

You can run the packaged application like this:
----
java -jar target/bddtrader-1.0.0-SNAPSHOT.jar -Ddata.source==IEX
----

If you want to run the application using live data, you can run the following command:

----
java -Ddata.source==IEX -jar target/bddtrader-1.0.0-SNAPSHOT.jar
----

You can also start the application from the command line by running `mvn springboot:run`, or,
to run the application using live market data, you can run `mvn spring-boot:run -Ddata.source=IEX`.


=== Running the tests

You can run the full test suite by running `mvn verify`.

=== The application domain

The application manages Clients, who own Portfolios of shares. Clients can buy and sell shares
at market rates, and the service keeps track of the transactions and of the client's current position.

Clients need to register with the service by providing their name and an email address.